import { Inter } from "next/font/google";
import "./globals.css";
import "./all.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ReduxProvider from "./components/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en" data-theme="black">
      <body className={`${inter.className}`}>
        <ReduxProvider>
          <SessionProvider session={session}>
            {children}
            <ToastContainer />
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
